%% ── FIGURE : Débattement angulaire des molettes ──────────────────────────────
figure('Name','Débattement molettes','Color','w','Position',[400 400 800 500]);
hold on; grid on; axis equal;
 
% ── Paramètres des molettes ───────────────────────────────────────────────────
petite_D =  -58;    % degrés vers la droite
petite_G = 73;    % degrés vers la gauche
grande_D =  -142;
grande_G = 87;
% ── Rayons (visuels) ──────────────────────────────────────────────────────────
r_petite = 1;
r_grande = 1.6;
 
% ── Arcs ──────────────────────────────────────────────────────────────────────
theta_petite = linspace(petite_G, petite_D, 300);
theta_grande = linspace(grande_G, grande_D, 300);
 
plot(r_petite * cosd(theta_petite + 90), r_petite * sind(theta_petite + 90), ...
     '-', 'Color', [0.2 0.4 0.9], 'LineWidth', 4, 'DisplayName', 'Petite molette');
plot(r_grande * cosd(theta_grande + 90), r_grande * sind(theta_grande + 90), ...
     '-', 'Color', [0.9 0.2 0.2], 'LineWidth', 4, 'DisplayName', 'Grande molette');
 
% ── Position initiale (0°) — en haut ─────────────────────────────────────────
plot(0, +r_petite, 'diamond', 'MarkerSize', 12, ...
     'MarkerEdgeColor', [0.1 0.3 0.8], 'MarkerFaceColor', 'white', ...
     'LineWidth', 2, 'HandleVisibility', 'off');
plot(0, +r_grande, 'diamond', 'MarkerSize', 12, ...
     'MarkerEdgeColor', [0.8 0.1 0.1], 'MarkerFaceColor', 'white', ...
     'LineWidth', 2, 'HandleVisibility', 'off');
 
% ── Marqueurs extrêmes ────────────────────────────────────────────────────────
plot(r_petite * cosd(petite_D + 90), r_petite * sind(petite_D + 90), ...
     '>', 'MarkerSize', 11, 'MarkerEdgeColor', [0.1 0.3 0.8], ...
     'MarkerFaceColor', [0.2 0.4 0.9], 'LineWidth', 2, 'HandleVisibility', 'off');
plot(r_petite * cosd(petite_G + 90), r_petite * sind(petite_G + 90), ...
     '<', 'MarkerSize', 11, 'MarkerEdgeColor', [0.1 0.3 0.8], ...
     'MarkerFaceColor', [0.2 0.4 0.9], 'LineWidth', 2, 'HandleVisibility', 'off');
plot(r_grande * cosd(grande_D + 90), r_grande * sind(grande_D + 90), ...
     '>', 'MarkerSize', 11, 'MarkerEdgeColor', [0.8 0.1 0.1], ...
     'MarkerFaceColor', [0.9 0.2 0.2], 'LineWidth', 2, 'HandleVisibility', 'off');
plot(r_grande * cosd(grande_G + 90), r_grande * sind(grande_G + 90), ...
     '<', 'MarkerSize', 11, 'MarkerEdgeColor', [0.8 0.1 0.1], ...
     'MarkerFaceColor', [0.9 0.2 0.2], 'LineWidth', 2, 'HandleVisibility', 'off');
 
% ── Lignes radiales ───────────────────────────────────────────────────────────
plot([0, r_petite * cosd(petite_D + 90)], [0, r_petite * sind(petite_D + 90)], ...
     '--', 'Color', [0.2 0.4 0.9 0.5], 'LineWidth', 1, 'HandleVisibility', 'off');
plot([0, r_petite * cosd(petite_G + 90)], [0, r_petite * sind(petite_G + 90)], ...
     '--', 'Color', [0.2 0.4 0.9 0.5], 'LineWidth', 1, 'HandleVisibility', 'off');
plot([0, 0], [0, +r_petite], '--', 'Color', [0.2 0.4 0.9 0.5], ...
     'LineWidth', 1, 'HandleVisibility', 'off');
plot([0, r_grande * cosd(grande_D + 90)], [0, r_grande * sind(grande_D + 90)], ...
     '--', 'Color', [0.9 0.2 0.2 0.5], 'LineWidth', 1, 'HandleVisibility', 'off');
plot([0, r_grande * cosd(grande_G + 90)], [0, r_grande * sind(grande_G + 90)], ...
     '--', 'Color', [0.9 0.2 0.2 0.5], 'LineWidth', 1, 'HandleVisibility', 'off');
plot([0, 0], [0, +r_grande], '--', 'Color', [0.9 0.2 0.2 0.5], ...
     'LineWidth', 1, 'HandleVisibility', 'off');
 
% ── Annotations des angles aux extrêmes ──────────────────────────────────────
text(r_petite * cosd(petite_D + 90) + 0.05, r_petite * sind(petite_D + 90), ...
     sprintf('%d°', petite_D), 'Color', [0.2 0.4 0.9], 'FontSize', 11, 'FontWeight', 'bold');
text(r_petite * cosd(petite_G + 90) - 0.15, r_petite * sind(petite_G + 90), ...
     sprintf('%d°', petite_G), 'Color', [0.2 0.4 0.9], 'FontSize', 11, 'FontWeight', 'bold');
text(r_grande * cosd(grande_D + 90) + 0.05, r_grande * sind(grande_D + 90), ...
     sprintf('%d°', grande_D), 'Color', [0.9 0.2 0.2], 'FontSize', 11, 'FontWeight', 'bold');
text(r_grande * cosd(grande_G + 90) - 0.18, r_grande * sind(grande_G + 90), ...
     sprintf('%d°', grande_G), 'Color', [0.9 0.2 0.2], 'FontSize', 11, 'FontWeight', 'bold');
 
% ── Totaux en bas ─────────────────────────────────────────────────────────────
text(0, -r_petite - 0.15, sprintf('Petite : %d° total', abs(petite_D) + abs(petite_G)), ...
     'Color', [0.2 0.4 0.9], 'FontSize', 10, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');
text(0, -r_grande - 0.15, sprintf('Grande : %d° total', abs(grande_D) + abs(grande_G)), ...
     'Color', [0.9 0.3 0.2], 'FontSize', 10, 'FontWeight', 'bold', 'HorizontalAlignment', 'center');
 
% ── Centre ────────────────────────────────────────────────────────────────────
plot(0, 0, 'k+', 'MarkerSize', 12, 'LineWidth', 2, 'HandleVisibility', 'off');
 
lgd = legend('Location', 'southoutside', 'Orientation', 'horizontal', 'FontSize', 11);
lgd.Position(2) = lgd.Position(2) - 0.08;
title({'Débattement angulaire des molettes', '◇ = position initiale   ▶ = extrême D   ◀ = extrême G'});
axis off;
